language: bash
services: docker

env:
  - VARIANT=debian
  - VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="rabbitmq:$VARIANT"

script:
  - docker build -t "$image" "$VARIANT"
  - ~/official-images/test/run.sh "$image"
  - docker build -t "${image}-management" "$VARIANT/management"
  - ~/official-images/test/run.sh "${image}-management"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
